# Generated by Django 3.2.4 on 2021-06-08 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('products', '0001_initial'),
        ('users', '0006_alter_user_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='product_order_item',
            field=models.ManyToManyField(related_name='product_order_item', through='orders.OrderItem', to='products.Product'),
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'db_table': 'likes',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='product_like',
            field=models.ManyToManyField(related_name='product_like', through='users.Like', to='products.Product'),
        ),
    ]
