# Generated by Django 3.2.4 on 2021-06-09 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210609_1544'),
        ('users', '0008_auto_20210609_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='likes',
            field=models.ManyToManyField(through='users.Like', to='products.Product'),
        ),
    ]
