# Generated by Django 3.2.4 on 2021-06-09 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210609_1544'),
        ('users', '0009_alter_user_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='likes',
        ),
        migrations.AddField(
            model_name='user',
            name='likes',
            field=models.ManyToManyField(to='products.Product'),
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
