# Generated by Django 3.2.4 on 2021-06-09 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20210609_1620'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='likes',
            new_name='product',
        ),
    ]
