# Generated by Django 3.2.4 on 2021-06-09 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20210609_1623'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='likes',
            new_name='like',
        ),
        migrations.AlterField(
            model_name='like',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_user', to='users.user'),
        ),
    ]
