# Generated by Django 3.2.4 on 2021-06-09 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210609_0837'),
        ('users', '0013_auto_20210609_1634'),
    ]

    operations = [
    ]
