# Generated by Django 2.2.12 on 2021-06-17 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20210616_1226'),
        ('users', '0018_merge_20210611_2349'),
    ]

    operations = [
    ]
