# Generated by Django 2.2.12 on 2021-06-11 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20210611_1257'),
        ('orders', '0004_auto_20210610_1637'),
    ]

    operations = [
    ]
