# Generated by Django 3.2.4 on 2021-06-15 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20210614_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
