# Generated by Django 2.2.12 on 2021-06-16 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_merge_20210611_2349'),
        ('orders', '0008_auto_20210615_1553'),
    ]

    operations = [
    ]
