# Generated by Django 2.2.12 on 2021-06-17 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20210616_1226'),
        ('orders', '0009_merge_20210616_1516'),
    ]

    operations = [
    ]
