# Generated by Django 3.2.4 on 2021-06-09 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='sub_category',
            new_name='sub_name',
        ),
        migrations.RemoveField(
            model_name='imagetype',
            name='image_type',
        ),
        migrations.RemoveField(
            model_name='productinfo',
            name='product',
        ),
        migrations.AddField(
            model_name='imagetype',
            name='type',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='product_info',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='products.productinfo'),
        ),
    ]
