# Generated by Django 3.2.4 on 2021-06-09 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210609_1544'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productinfo',
            old_name='manufaturer',
            new_name='manufacturer',
        ),
    ]
