# Generated by Django 3.2.4 on 2021-06-11 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210609_1834'),
    ]

    operations = [

        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(max_length=255, unique=True),
        ),

    ]
