# Generated by Django 2.2.12 on 2021-06-10 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20210610_1637'),
    ]


