# Generated by Django 3.2.4 on 2021-06-11 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20210611_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='korean_name',
            field=models.CharField(max_length=50, unique=True,null=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subcategory',
            name='korean_name',
            field=models.CharField(max_length=50, unique=True,null=True),
            preserve_default=False,
        ),
    ]
