# Generated by Django 3.2.4 on 2021-06-11 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20210611_1329'),
    ]

<<<<<<< HEAD
=======
    operations = [
        migrations.RemoveField(
            model_name='category',
            name='korean_name',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='korean_name',
        ),
        migrations.AddField(
            model_name='category',
            name='korean_name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='korean_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
>>>>>>> main
