# Generated by Django 3.2.4 on 2021-06-11 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20210611_1329'),
    ]

