# Generated by Django 3.2.4 on 2021-06-11 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20210611_1353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='english_name',
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='name',
            new_name='english_name',
        ),
    ]
