# Generated by Django 2.2.12 on 2021-06-11 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20210611_1353'),
        ('products', '0006_auto_20210610_1756'),
    ]

    operations = [
    ]
