# Generated by Django 3.2.4 on 2021-06-14 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20210611_1353'),
    ]

    operations = [

    ]
