# Generated by Django 3.2.4 on 2021-06-14 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20210614_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image_url',
            field=models.CharField(max_length=255),
        ),
    ]
