# Generated by Django 2.2.12 on 2021-06-12 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20210611_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='korean_name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='korean_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
