# Generated by Django 3.2.4 on 2021-06-15 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20210614_1853'),
    ]

    operations = [

        migrations.AddField(
            model_name='product',
            name='main_image',
            field=models.CharField(default='0', max_length=255),
        ),
    ]
