# Generated by Django 3.2.4 on 2021-06-15 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20210615_1553'),
    ]

    operations = [

        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=models.CharField(max_length=255),
        ),
    ]
