# Generated by Django 3.2.4 on 2021-06-15 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20210615_1553'),
    ]

    operations = [

    ]
