# Generated by Django 2.2.12 on 2021-06-16 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20210612_0006'),
        ('products', '0011_auto_20210615_1553'),
    ]

    operations = [
    ]
