# Generated by Django 2.2.12 on 2021-06-17 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20210615_1912'),
        ('products', '0012_merge_20210616_1516'),
        ('products', '0012_auto_20210616_1226'),
    ]

    operations = [
    ]
