# Generated by Django 3.2.4 on 2021-06-16 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20210615_1912'),
        ('products', '0012_merge_20210616_1516'),
    ]

    operations = [
    ]
